accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', login,
        {'template_name': 'accounts/login.html'},
        name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup')
]

pytter/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django_js_reverse.views

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^api/tweets', include('tweet_api.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^jsreverse/$', django_js_reverse.views.urls_js, name='js_reverse'),
    url(r'^', include('tweet.urls')),
]

tweet/urls.py
from django.conf.urls import url

from . import views

app_name = 'tweet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tweet$', views.tweet, name='tweet'),
    url(r'^who_to_follow$', views.who_to_follow, name='who_to_follow'),
    url(r'^toggle_follow/(?P<account_id>[^/]+)$', views.toggle_follow, name='toggle_follow'),
    url(r'^(?P<author_name>[^/]+)/status/(?P<tweet_id>\d+)$', views.show_tweet, name='show_tweet'),
]

tweet_api/urls.py
from django.conf.urls import url

from . import views

app_name = 'tweet_api'
urlpatterns = [
    url(r'^$', views.tweets, name='tweets'),
    url(r'^/post$', views.post_tweet, name='post_tweet'),
    url(r'^(?P<author_name>[^/]+)/status/(?P<tweet_id>\d+)$', views.get_tweet, name='get_tweet'),
]

accounts/models.py
from django.db import models

# Create your models here.

tweet/models.py
from django.db import models
from django.conf import settings
from django.forms.models import model_to_dict

class Account(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=100)
    display_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    blocked_at = models.DateTimeField(null=True, blank=True)

    follows = models.ManyToManyField(
        "self",
        symmetrical = False,
        related_name = "followers",
        related_query_name = "follower"
    )

    def __str__(self):
        return self.name

    def to_dict(self):
        return model_to_dict(
            self,
            fields=['id', 'name', 'display_name']
        )


class Tweet(models.Model):
    author = models.ForeignKey(
        Account,
        on_delete = models.CASCADE,
        related_name = "tweets",
        related_query_name = "tweet"
    )
    text = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True)

    retweet_from = models.ForeignKey(
        'Tweet',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return str(self.pk)

    def to_dict(self):
        return {
            'id': self.id,
            'text': self.text,
            'author': self.author.to_dict(),
            'created_at': self.created_at,
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate

from tweet.models import Account

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        displayName = request.POST.get('displayname')
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            Account.objects.create(
                user = user,
                name = username,
                display_name = request.POST['displayname']
            )

            login(request, user)
            return redirect('tweet:index')
    else:
        form = UserCreationForm()
        displayName = ''
    return render(request, 'accounts/signup.html',
                  {'form': form, 'displayName': displayName})

tweet/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from .models import Account, Tweet

@login_required
def index(request):
    account = request.user.account
    follows = account.follows.all()
    followers = account.followers.all()

    return render(request, 'tweet/index.html', {
        'follows': follows,
        'followers': followers,
    })

@login_required
def who_to_follow(request):
    account = request.user.account
    follows = account.follows.all()
    accounts = Account.objects.exclude(pk=account.pk)

    return render(request, 'tweet/who_to_follow.html', {
        'follows': follows,
        'accounts': accounts,
    })

@login_required
def toggle_follow(request, account_id):
    followed = get_object_or_404(Account, pk = account_id)

    account = request.user.account
    if account.follows.filter(pk=followed.pk).exists():
        account.follows.remove(followed)
    else:
        account.follows.add(followed)

    return redirect('tweet:who_to_follow')


# -----
# react 以前のときの実装
@login_required
def tweet(request):
    account = request.user.account
    text = request.POST['text']

    Tweet.objects.create(
        author = account,
        text = text,
    )
    return redirect('tweet:index')

@login_required
def show_tweet(request, author_name, tweet_id):
    author = Account.objects.get(name = author_name)
    tweet = author.tweets.get(pk = tweet_id)

    return render(request, 'tweet/show_tweet.html', {
        'author': author,
        'tweet': tweet,
    })

tweet_api/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import F, Q
from tweet.models import Account, Tweet

@login_required
def tweets(request):
    account = request.user.account

    tweets = Tweet.objects.filter(
        Q(author__in = Account.objects.filter(follows = account)) | \
        Q(author = account)
    )

    if 'since' in request.GET and \
        request.GET['since'] != 'null':
        tweets = tweets.filter(
            created_at__gt = request.GET['since']
        )

    tweets = tweets.order_by('-created_at')

    return JsonResponse({
        'tweets': [ tweet.to_dict() for tweet in tweets]
    })

@login_required
def post_tweet(request):
    account = request.user.account
    text = request.POST['text']

    tweet = Tweet.objects.create(
        author = account,
        text = text,
    )
    return JsonResponse(tweet.to_dict())

@login_required
def get_tweet(request, author_name, tweet_id):
    author = Account.objects.get(name = author_name)
    tweet = author.tweets.get(pk = tweet_id)

    return JsonResponse(tweet.to_dict())

accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}
<html lang="ja">
<head>
  <title>{% block title %}Twitter clone{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <script src="{% url 'js_reverse' %}" type="text/javascript"></script>

  <style>
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }

  header {
    height: 64px;
  }

  main {
    flex: 1 0 auto;
  }

  section {
    margin-top: 1.5em;
  }
  </style>

</head>

<body>
<header>
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center">Pytter</a>
    </div>
  </nav>
</header>

<main>
  {% block content %}{% endblock %}
</main>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      © Copyright
    </div>
  </div>
</footer>
</body>
</html>

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block content %}
<section>
  <div class="container">
    <section class="section">

      <form action="{% url 'accounts:login' %}" method="post" role="form">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ next }}"/>

        {% if form.errors  %}
          <div class="row">
            <div class="col s8 offset-s2">
              <div class="alert alert-danger" role="alert">
                <p>Your usernamne and password didn't match. Please try again.</p>
              </div>
            </div>
          </div>
        {% endif %}

        <div class="row">
          <div class="col s6 offset-s3">

            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <input id="username" name="username" type="text" value=""
                  maxlength="256" autofocus required/>
                <label for="username">Username</label>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <input id="password" name="password" type="password" value=""
                  maxlength="256" required/>
                <label for="password">Password</label>
              </div>
            </div>

            <div class="row">
              <div class="col s12">
                <button type="submit" class="btn waves-effect waves-light">
                  <i class="material-icons left">power_settings_new</i>Login
                </button>

                <a class="btn waves-effect waves-light blue right"
                   href="{% url 'accounts:signup' %}">
                  <i class="material-icons left">person_add</i>Signup
                </a>
              </div>
            </div>

          </div>
        </div>

      </form>

      <div class="row section">
        <div class="col s6 offset-s3">
        </div>
      </div>

    </section>
  </div>
</section>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}

{% block content %}
<section>
  <div class="container">
    <section class="section">

      <form action="{% url 'accounts:signup' %}" method="post" role="form">
        {% csrf_token %}

        <div class="row">
          <div class="col s6 offset-s3">
            {% for field in form %}
              <div class="row">
                <div class="input-field col s12">
                  <i class="material-icons prefix">
                    {% cycle 'account_circle' 'vpn_key' 'vpn_key' %}
                  </i>
                  {{ field }}
                  {{ field.label_tag }}

                  {% comment %}
                  {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                  {% endif %}
                  {% endcomment %}

                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}

            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">face</i>
                <input id="displayname" type="text"
                       name="displayname" value="{{ displayName }}"
                       maxlength="256" required/>
                <label for="displayname">名前</label>
              </div>
            </div>

            <div class="row">
              <div class="col s12">
                <button type="submit" class="btn waves-effect waves-light">
                  <i class="material-icons left">power_settings_new</i>Signup
                </button>
              </div>
            </div>

          </div>
        </div>

      </form>

    </section>
  </div>
</section>
{% endblock %}

tweet/templates/tweet/base.html
<!DOCTYPE html>
{% load render_bundle from webpack_loader %}
<html lang="ja">
<head>
  <title>{% block title %}Twitter clone{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <script src="{% url 'js_reverse' %}" type="text/javascript"></script>

  <style>
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }

  header {
    height: 64px;
  }

  main {
    flex: 1 0 auto;
  }

  section {
    margin-top: 1.5em;
  }

  #dropdown__account {
    margin-top: 64px;
  }
  </style>

</head>

<body>
  <header>
    <nav>
      <div class="nav-wrapper">
        <div class="container">
          <a href="{% url 'tweet:index' %}" class="brand-logo">
            <i class="material-icons left">home</i>
            Pytter
          </a>

          <ul class="right">
            <li>
              <a href="{% url 'tweet:who_to_follow' %}" >
                <i class="material-icons left">person_add</i>
                フォロー
              </a>
            </li>

            <li>
              <a class="dropdown-button" href="#!"
                 data-activates="dropdown__account">
                <i class="material-icons left">account_circle</i>

                {{ request.user.account.display_name }}
                ( @{{ request.user.account.name }} )
                <i class="material-icons right">arrow_drop_down</i>
              </a>
            </li>
          </ul>

        </div>
      </div>
    </nav>
    <ul id="dropdown__account" class="dropdown-content">
      <li>
        <a href="{% url 'accounts:logout' %}">logout</a>
      </li>
    </ul>
  </header>

  <main>
    {% block content %}{% endblock %}
  </main>

  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script>$(".dropdown-button").dropdown({ hover: false });</script>
  {% render_bundle 'main' %}

  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
        © Copyright
      </div>
    </div>
  </footer>
</body>
</html>

tweet/templates/tweet/index.html
{% extends 'tweet/base.html' %}

{% block content %}
<section>
  <div class="container">
    <div class="row">
      <div class="col s12">
        <span  class="grey-text">Following:</span>
        <b>{{ follows | length }}</b>

        &nbsp;&nbsp;

        <span  class="grey-text">Followers:</span>
        <b>{{ followers | length }}</b>

      </div>
    </div>

    <div id="root"></div>

  </div>
</section>
{% endblock %}

tweet/templates/tweet/show_tweet.html
{% extends 'tweet/base.html' %}

{% block content %}
<div>
  <a href="{% url 'accounts:logout' %}">logout</a>
</div>

<div>
  Tweet
</div>
<div>
  {{ request.user }}
</div>

<div>
  {{ tweet.text }}
</div>

<pre>
  {{ tweet| pprint }}
</pre>
<pre>
{{ author | pprint }}
</pre>
{% endblock %}

tweet/templates/tweet/who_to_follow.html
{% extends 'tweet/base.html' %}

{% block content %}
<style>
  .collection .collection-item.avatar {
    min-height: 42px;
    padding-left: 52px;
  }

  .collection .collection-item.avatar:not(.circle-clipper)>.circle,
  .collection .collection-item.avatar :not(.circle-clipper)>.circle {
    width: 21px;
    height: 21px;
  }

  .collection .collection-item.avatar .avatar-initial {
    font-weight: bold;
    text-align: center;
    vertical-align: middle;
    line-height: 21px;
  }

  .collection .collection-item.avatar .secondary-content {
    top: 12px;
  }
</style>
<section>
  <div class="container">

    <div class="row">
      <div class="col s12 section">
        <div>
          <b>following:</b>

          {% for acc in follows %}
          <div class="chip">
            {{ acc.name }}
          </div>
          {% empty %}
          なし
          {% endfor %}
        </div>

      </div>
    </div>

    <section>
      <h5>ユーザ一覧</h5>

      <div class="row">
        <div class="col s12 section">

          <ul class="collection">

            {% for acc in accounts %}
              <li class="collection-item avatar">
                <span class="circle avatar-initial orange white-text">
                  {{ acc.name | first | upper }}
                </span>
                <span class="title">
                  {{ acc.display_name }}
                  <small class="gray-text">@{{ acc.name }}</small>
                </span>
                <a href="{% url 'tweet:toggle_follow' acc.id %}" class="secondary-content">
                  {% if acc in follows %}
                    フォローをはずす
                  {% else %}
                    フォローする
                  {% endif %}
                </a>
              </li>
            {% empty %}
              なし
            {% endfor %}
          </ul>

        </div>
      </div>

    </section>

  </div>
</section>
{% endblock %}